#![no_std]
#![no_main]
//! Aya rendering of the CO-RE reader. Aya does CO-RE transparently *when the
//! bindings carry BTF* — i.e. when src/vmlinux.rs is generated by `aya-tool
//! generate task_struct`. With the placeholder bindings this compiles but won't
//! relocate; regenerate them (see src/vmlinux.rs). The canonical, definitely-
//! relocating version is reference/core.bpf.c.

mod vmlinux;

use aya_ebpf::{
    helpers::bpf_get_current_task,
    macros::{kprobe, map},
    maps::Array,
    programs::ProbeContext,
};
use vmlinux::task_struct;

#[map] static READS: Array<u64> = Array::with_max_entries(1, 0);

#[kprobe]
pub fn count_reads(_ctx: ProbeContext) -> u32 {
    let task = unsafe { bpf_get_current_task() as *const task_struct };
    if task.is_null() {
        return 0;
    }
    // Reading a field on the generated binding is what emits a CO-RE relocation
    // (with real aya-tool bindings). Offsets are resolved from the target BTF.
    let _pid = unsafe { (*task).pid };

    if let Some(c) = READS.get_ptr_mut(0) {
        unsafe { *c += 1 };
    }
    0
}

#[cfg(not(test))]
#[panic_handler]
fn panic(_: &core::panic::PanicInfo) -> ! {
    loop {}
}
