FROM registry.access.redhat.com/ubi9/openjdk-21 AS build
WORKDIR /app
COPY Server.java .
RUN javac Server.java
FROM registry.access.redhat.com/ubi9/openjdk-21-runtime
WORKDIR /app
COPY --from=build /app/Server.class .
EXPOSE 8080
CMD ["java", "Server"]
