quarkus.application.name=ebpf-capstone-quarkus
quarkus.otel.exporter.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://host.containers.internal:4317}
quarkus.otel.resource.attributes=service.namespace=ebpf-with-aya
quarkus.http.port=8080
